name: "pr-status"
description: "A GitHub Action that checks the status of a pull request"
author: "Grant Birkinbine"
branding:
  icon: 'check'
  color: 'green'
inputs:
  github_token:
    description: The GitHub token used to create an authenticated client - Provided for you by default!
    default: ${{ github.token }}
    required: true
  pr_number:
    description: The number of the pull request to check the status of
    default: ${{ github.event.number }}
    required: true
  checks:
    description: Whether to only look for `required` ci checks or `all` ci checks on the pull request
    default: all
    required: true
  evaluations:
    description: The attributes to evaluate the pull request against when determining its status on a PASS/FAIL system. This plays into the `evaluation` output
    default: 'approved,ci_passing,mergeable' # this says that the pull request must be approved, have passing ci, and be mergeable
    required: false
outputs:
  approved:
    description: 'The string "true" if the pull request is in a fully approved state, "false" otherwise'
  total_approvals:
    description: 'The total number of approvals on the pull request'
  review_decision:
    description: 'The decision of the pull request review status - Examples: "APPROVED", "CHANGES_REQUESTED", "REVIEW_REQUIRED", `null`, etc'
  merge_state_status:
    description: 'The status of the pull request merge state - Examples: "CLEAN", "DIRTY", "UNKNOWN", "DRAFT", "BLOCKED", etc'
  commit_status:
    description: 'The ci status for the latest commit on the pull request - Examples: "SUCCESS", "FAILURE", "PENDING", `null`, etc'
  evaluation:
    description: 'The overall evaluation of the pull request based on the evaluations input - Examples: "PASS", "FAIL"'
runs:
  using: "node20"
  main: "dist/index.js"
  post: "dist/index.js"
